[package]
name = "mips-emulator"
version = "0.1.0"
edition = "2021"
default-run = "mme"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "mme"
path = "src/bin/main.rs"
