[package]
name = "mips-compiler"
version = "0.1.0"
edition = "2021"
default-run = "lazyer"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"]}


[[bin]]
name = "lazyer"
path = "src/bin/main.rs"
