[package]
name = "mips-compiler"
version = "0.1.0"
edition = "2021"
default-run = "lazyer"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"

[[bin]]
name = "lazyer"
path = "src/bin/main.rs"
